### ISSUE TITLE
Tree name must be "tree"

### ISSUE THREAD

**Issue by mortenmathiasen** [shinyTree/shinyTree#57]
Thank you for a great Shiny library!

For half a year I have succesfully been using the shinyTree like:
```
shinyTree("kompetenceTree", checkbox = TRUE)
...
observeEvent(input$kompetenceTree, ignoreInit = TRUE, { ... }) 
```

Today, I was moving the solution to use the newest version of shinyTree. To continue get notification calls on the observeEvent method I had to change the trees name:
```
shinyTree("tree", checkbox = TRUE)
...
observeEvent(input$tree, ignoreInit = TRUE, { ... }) 
```

The bug that forces this name change has been introduced within the last 6 months.

**Comment by bellma-lilly** [comment]
Sorry for the trouble; thanks for the bug report.  I will look into this.

**Comment by tcash21** [comment]
We have to use two trees in a particular Shiny app right now, there's no workaround currently that you know of?

**Comment by bellma-lilly** [comment]
I am not able to reproduce this problem.  I can use the treeName "kompetenceTree" and I can use two trees at the same time with different names.

Are you using the cran version or the most up to date version on github?

**Comment by mortenmathiasen** [comment]
I installed the library by following this instruction:
install.packages("devtools")
library(devtools)
install_github("shinyTree/shinyTree")

**Comment by trafficonese** [comment]
I am also not able to reproduce that error. I can name the tree whatever I want.

**Comment by SamGG** [comment]
Hi,
I got the exact same error. I think it comes from a JS problem. My Vivaldi (Chrome) complains about the following error in the console: `document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.`
HTH

**Comment by YsoSirius** [comment]
This was a warning for a long time but I dont think it hinders us from naming the tree differently. Also, this issue #48 is about the same warning.

Anyway, the PR #61 updates jsTree to 3.3.7, although this problem (document.registerElement) was already solved in 3.3.6. 

I tested 3.3.7 for a while now on my fork and there seems to be no problem with that version.

**Comment by SamGG** [comment]
Thanks for your answer. I installed your version as shinyTree library. Still can't get selected value when tree is not named "tree"...

**Comment by SamGG** [comment]
Thanks for your answer. I installed your version as shinyTree library. Still can't get selected value when tree is not named "tree".

Here are the messages I get in the console when replacing the name "tree" by "tree2". Javascript is definitively not my cup of tea.

```
shinyTree.js:60 Uncaught TypeError: $(...).jstree(...).get_node is not a function
    at Object.<anonymous> (shinyTree.js:60)
    at Function.each (jquery.min.js:2)
    at arrToObj (shinyTree.js:57)
    at fixOutput (shinyTree.js:92)
    at Object.<anonymous> (shinyTree.js:76)
    at Function.each (jquery.min.js:2)
    at fixOutput (shinyTree.js:74)
    at Object.<anonymous> (shinyTree.js:76)
    at Function.each (jquery.min.js:2)
    at fixOutput (shinyTree.js:74)
```

**Comment by YsoSirius** [comment]
Indeed, the current dev-version has this problem because of this line:
https://github.com/shinyTree/shinyTree/blob/ba38ac90318f7538bec47d6ced77acedaa3afc52/inst/www/shinyTree.js#L60

The tree is rendered correctly, but the selection methods dont work.

The CRAN version works fine though.

**Comment by SamGG** [comment]
Too complicated for me. I can live with the dev version because I am working with a single tree that I could call "tree". I can't work with the CRAN version as it is lacking of get_selected method IIRC.
Hope you developers could fix the problem for other users.
Thanks for this useful package.

**Comment by obkhan** [comment]
I’m having the same issue, in particular when modulation with callModule in which a namespace is used
