### ISSUE TITLE
updateTree() not working in shiny modules

### ISSUE THREAD

**Issue by fungs** [shinyTree/shinyTree#84]
updateTree() is recommended to be used when node selection does not trigger `observeEvent(input$tree, {})` after the output is changed via renderTree.

Unfortunately, at least for me, the same tree that draws well with renderTree() does not work with updateTree() because the displayed tree remains empty. This happens if run in a Shiny module.

My suspicion is that it is caused by the fact, that session is a different kind of object in a shiny module or because the given tree identifier does not match the one defined in the UI using the names namespace wrapper function `NS("id")("tree_id")`.

I'm sorry I cannot be more verbose with an example but it should be straightforward to reproduce.

**Comment by trafficonese** [comment]
Can you include a small example of that issue?

Maybe it is related to #81 and I just opened a PR (#85) which should fix it. Maybe it fixes your issue aswell?

**Comment by fungs** [comment]
Please leave this issue open, I will try to come with more details once I'm back to implementing this functionality in code. Thanks.

**Comment by trafficonese** [comment]
Is this still an issue?

**Comment by psimm** [comment]
I still see the issue with the current version of shinyTree from Master branch. Here is an example of an app with a shinyTree and an actionButton that should select all nodes. updateTree works without the module but doesn't do anything when used within the module.

**With module (doesn't work)**
```
library(shiny)
library(shinyTree)

treeModuleUI <- function(id) {
  ns <- NS(id)
  tagList(
    shinyTree(outputId = ns("tree"), checkbox = TRUE),
    actionButton(inputId = ns("select"), label = "Select all")
  )
}

treeModule <- function(input, output, session) {
  ns <- session$ns
  
  data <- list(root1 = "", root2 = "", root3 = "")
  output$tree <- renderTree(data)
  
  observeEvent(input$select, {
    message("Clicked on select all")
    for (i in seq_along(data)) {
      attr(data[[i]], "stselected") <- TRUE
    }
    updateTree(session, treeId = ns("tree"), data = data)
  })
} 

ui <- fluidPage(
  treeModuleUI(id = "tree1")
)

server <- function(input, output, session) {
  callModule(treeModule, id = "tree1")
}

shinyApp(ui, server)
```

**Without module (works)**
```
library(shiny)
library(shinyTree)

ui <- fluidPage(
  shinyTree(outputId = "tree", checkbox = TRUE),
  actionButton(inputId = "select", label = "Select all")
)

server <- function(input, output, session) {
  data <- list(root1 = "", root2 = "", root3 = "")
  output$tree <- renderTree(data)
  
  observeEvent(input$select, {
    message("Clicked on select all")
    
    for (i in seq_along(data)) {
      attr(data[[i]], "stselected") <- TRUE
    }
    updateTree(session, treeId = "tree", data = data)
  })
}

shinyApp(ui, server)
```

**Comment by psimm** [comment]
I still see the issue with the current version of shinyTree from Master branch. Here is an example of an app with a shinyTree and an actionButton that should select all nodes. updateTree works without the module but doesn't do anything when used within the module.

**With module (doesn't work)**
```
library(shiny)
library(shinyTree)

treeModuleUI <- function(id) {
  ns <- NS(id)
  tagList(
    shinyTree(outputId = ns("tree"), checkbox = TRUE),
    actionButton(inputId = ns("select"), label = "Select all")
  )
}

treeModule <- function(input, output, session) {
  ns <- session$ns
  
  data <- list(root1 = "", root2 = "", root3 = "")
  output$tree <- renderTree(data)
  
  observeEvent(input$select, {
    message("Clicked on select all")
    for (i in seq_along(data)) {
      attr(data[[i]], "stselected") <- TRUE
    }
    updateTree(session, treeId = ns("tree"), data = data)
  })
} 

ui <- fluidPage(
  treeModuleUI(id = "tree1")
)

server <- function(input, output, session) {
  callModule(treeModule, id = "tree1")
}

shinyApp(ui, server)
```

**Without module (works)**
```
library(shiny)
library(shinyTree)

ui <- fluidPage(
  shinyTree(outputId = "tree", checkbox = TRUE),
  actionButton(inputId = "select", label = "Select all")
)

server <- function(input, output, session) {
  data <- list(root1 = "", root2 = "", root3 = "")
  output$tree <- renderTree(data)
  
  observeEvent(input$select, {
    message("Clicked on select all")
    
    for (i in seq_along(data)) {
      attr(data[[i]], "stselected") <- TRUE
    }
    updateTree(session, treeId = "tree", data = data)
  })
}

shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
Try without `ns` for the updateTree:
`updateTree(session, treeId = "tree", data = data)`
That worked for me.

**Comment by fungs** [comment]
Just to understand: how does updateTree() know the correct shiny context? It seems it does infer the correct namespace somehow.

**Comment by trafficonese** [comment]
From my understanding, this is just normal shiny module magic, `updateTree` is called inside the server-part of the module and `ns()` normally should just be called within the UI functions. 
You can also see that `observeEvent` is triggered by `input$select` without the need of adding the module-namespace.
